### ISSUE TITLE
add code_of_conduct.md file to repository

### ISSUE THREAD

**Issue by tejan-singh** [priyanshux/FPL-Defence-Rotations#7]
- code_of_conduct.md file is missing in the repository. I would like to add one.

**Comment by priyanshux** [comment]
Sorry, but I don't support stat padding. **[1]** Do let me know if you'd like to work on any other issue. **[2][3]**

References:
**[1]** https://www.urbandictionary.com/define.php?term=stat%20padding
**[2]** https://github.com/priyanshux/FPL-Defence-Rotations#updates-issues-and-to-do
**[3]** https://github.com/priyanshux/FPL-Defence-Rotations/issues
