### ISSUE TITLE
add contributing.md file to repository

### ISSUE THREAD

**Issue by tejan-singh** [priyanshux/FPL-Defence-Rotations#8]
- I would like to add a contributing.md file to the repository consisting of all general and necessary guidelines.

**Comment by priyanshux** [comment]
Sorry, but I don't support stat padding. **[1]** Do let me know if you'd like to work on any other issue. **[2][3]**

References:
**[1]** https://www.urbandictionary.com/define.php?term=stat%20padding
**[2]** https://github.com/priyanshux/FPL-Defence-Rotations#updates-issues-and-to-do
**[3]** https://github.com/priyanshux/FPL-Defence-Rotations/issues
